### ISSUE TITLE
[Android] Compiling under/targeting SDK 30 causes crash on startup

### ISSUE THREAD

**Issue by cwhenderson20** [CleverTap/clevertap-react-native#112]
I've been able to reliably reproduce this startup crash on Android when targeting SDK 30 (targeting 29 shows no such issue).

```
FATAL EXCEPTION: Thread-4
Process: com.gridwise.app, PID: 11067
java.lang.SecurityException: getDataNetworkTypeForSubscriber
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3021)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2985)
	at com.clevertap.android.sdk.DeviceInfo$DeviceCachedInfo.getNetworkType(DeviceInfo.java:618)
	at com.clevertap.android.sdk.DeviceInfo$DeviceCachedInfo.<init>(DeviceInfo.java:546)
	at com.clevertap.android.sdk.DeviceInfo.getDeviceCachedInfo(DeviceInfo.java:81)
	at com.clevertap.android.sdk.DeviceInfo.access$000(DeviceInfo.java:23)
	at com.clevertap.android.sdk.DeviceInfo$1.run(DeviceInfo.java:52)
	at java.lang.Thread.run(Thread.java:923)
```

`getNetworkType` is deprecated in Android 11; `getDataNetworkType` should be used instead. [Here](https://github.com/mapbox/mapbox-gl-native-android/issues/425) is a thread about the issue and [the PR](https://github.com/mapbox/mapbox-events-android/pull/492) that fixed it.

**Comment by darshanclevertap** [comment]
@cwhenderson20 We've fixed this in our core Android SDK, we'll be releasing the React Native version with this fix in a couple of days.

**Comment by piyush-kukadiya** [comment]
@cwhenderson20 Release `v0.5.0` fixes this issue. Please update your package.
