### ISSUE TITLE
Getting error in Android SDK 16 . Clevertap initialization React native

### ISSUE THREAD

**Issue by dattaprasadPegasus** [CleverTap/clevertap-react-native#115]
I am getting following error : 

10-26 12:51:52.304 10829-10829/com.azam.sarafu E/dalvikvm: Could not find class 'android.app.job.JobScheduler', referenced from method com.clevertap.android.sdk.CleverTapAPI.createOrResetJobScheduler
10-26 12:51:52.684 10829-10882/com.azam.sarafu E/dalvikvm: Could not find class 'android.app.NotificationChannelGroup', referenced from method androidx.core.app.NotificationManagerCompat.getNotificationChannelGroup
10-26 12:51:52.694 10829-10885/com.azam.sarafu E/dalvikvm: Could not find class 'com.clevertap.android.sdk.pushnotification.amp.CTBackgroundJobService', referenced from method com.clevertap.android.sdk.ManifestValidator.checkReceiversServices
10-26 12:51:52.764 10829-10829/com.azam.sarafu E/dalvikvm: dlopen("/data/app-lib/com.azam.sarafu-2/libjscexecutor.so") failed: dlopen failed: could not load library "libjsc.so" needed by "libjscexecutor.so"; caused by library "libjsc.so" not found
10-26 12:51:52.764 10829-10829/com.azam.sarafu E/SoLoader: couldn't find DSO to load: libjscexecutor.so caused by: dlopen failed: could not load library "libjsc.so" needed by "libjscexecutor.so"; caused by library "libjsc.so" not found result: 0
10-26 12:51:52.784 10829-10829/com.azam.sarafu E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.azam.sarafu, PID: 10829
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.azam.sarafu/com.azam.sarafu.MainActivity}: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
        at android.app.ActivityThread.access$800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
        at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:90)
        at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:238)
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:281)
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87)
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39)
        at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:104)
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:90)
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:85)
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45)
        at com.azam.sarafu.MainActivity.onCreate(MainActivity.java:30)
        at android.app.Activity.performCreate(Activity.java:5231)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:80)
        at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:238) 
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:281) 
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87) 
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39) 
        at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:104) 
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:90) 
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:85) 
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45) 
        at com.azam.sarafu.MainActivity.onCreate(MainActivity.java:30) 
        at android.app.Activity.performCreate(Activity.java:5231) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.ExceptionInInitializerError
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015)
        at com.facebook.react.devsupport.DevServerHelper.<init>(DevServerHelper.java:132)
        at com.facebook.react.devsupport.DevSupportManagerImpl.<init>(DevSupportManagerImpl.java:183)
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
        at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:80) 
        at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:238) 
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:281) 
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87) 
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39) 
        at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:104) 
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:90) 
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:85) 
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45) 
        at com.azam.sarafu.MainActivity.onCreate(MainActivity.java:30) 
        at android.app.Activity.performCreate(Activity.java:5231) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 19
        at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
        at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263) 
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229) 
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015) 
        at com.facebook.react.devsupport.DevServerHelper.<init>(DevServerHelper.java:132) 
        at com.facebook.react.devsupport.DevSupportManagerImpl.<init>(DevSupportManagerImpl.java:183) 
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
        at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:80) 
        at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:238) 
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:281) 
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87) 
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39) 
        at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:104) 
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:90) 
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:85) 
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45) 
        at com.azam.sarafu.MainActivity.onCreate(MainActivity.java:30) 
        at android.app.Activity.performCreate(Activity.java:5231) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 

Using following configuration :

minSdkVersion : 16

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

    implementation "com.google.android.gms:play-services-base:17.5.0"
    implementation 'androidx.appcompat:appcompat:1.1.0-rc01'

    implementation 'com.google.firebase:firebase-analytics:17.6.0'
    implementation "androidx.core:core:1.3.0"
    implementation project(':clevertap-react-native')
    implementation project(':react-native-exception-handler')
    implementation project(':react-native-device-info')
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
implementation 'com.google.android.material:material:1.1.0'
  implementation 'com.clevertap.android:clevertap-android-sdk:4.0.0'
    implementation 'com.google.firebase:firebase-messaging:20.3.0'
    implementation 'com.android.installreferrer:installreferrer:2.1'
    implementation 'com.android.support:support-v4:28.0.0'
debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group :'com.facebook.fbjni'
    }

    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group :'com.facebook.flipper'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group :'com.facebook.flipper'
    }

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

package.json
 "clevertap-react-native": "^0.5.0",
 "react": "16.11.0",
    "react-native": "0.62.2",

Can anyone please guide regarding this.

**Comment by darshanclevertap** [comment]
@dattaprasadPegasus Is this a build time error or a run time crash?

**Comment by dattaprasadPegasus** [comment]
It's run time crash.

**Comment by dattaprasadPegasus** [comment]
@darshanclevertap any clue ?.

**Comment by darshanclevertap** [comment]
@dattaprasadPegasus Do you have the following entry in your `AndroidManifest.xml` file?
```xml
<meta-data
    android:name="CLEVERTAP_BACKGROUND_SYNC"
    android:value="1" />
```

**Comment by dattaprasadPegasus** [comment]
@darshanclevertap Yes, I have following lines in my AndroidManifest.xml.

<meta-data
            android:name="CLEVERTAP_BACKGROUND_SYNC"
            android:value="1" /> 
        <service
            android:name="com.clevertap.android.sdk.CTBackgroundIntentService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.clevertap.BG_EVENT" />
            </intent-filter>
        </service> 
        <service
            android:name="com.clevertap.android.sdk.CTBackgroundJobService"
            android:exported="false"
            android:permission="android.permission.BIND_JOB_SERVICE" />

**Comment by dattaprasadPegasus** [comment]
@darshanclevertap Yes, I have these line in my AndroidManifest.xml

<meta-data
            android:name="CLEVERTAP_BACKGROUND_SYNC"
            android:value="1" /> 
        <service
            android:name="com.clevertap.android.sdk.CTBackgroundIntentService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.clevertap.BG_EVENT" />
            </intent-filter>
        </service> 
        <service
            android:name="com.clevertap.android.sdk.CTBackgroundJobService"
            android:exported="false"
            android:permission="android.permission.BIND_JOB_SERVICE" />

**Comment by dattaprasadPegasus** [comment]
<meta-data
            android:name="CLEVERTAP_BACKGROUND_SYNC"
            android:value="1" /> 
            
        <service
            android:name="com.clevertap.android.sdk.CTBackgroundIntentService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.clevertap.BG_EVENT" />
            </intent-filter>
        </service>
         
        <service
            android:name="com.clevertap.android.sdk.CTBackgroundJobService"
            android:exported="false"
            android:permission="android.permission.BIND_JOB_SERVICE" />

**Comment by darshanclevertap** [comment]
@dattaprasadPegasus Since you're using CleverTap Android SDK v4.0.0, please remove the following from your manifest - 

```xml
    <service
        android:name="com.clevertap.android.sdk.CTBackgroundIntentService"
        android:exported="false">
        <intent-filter>
            <action android:name="com.clevertap.BG_EVENT" />
        </intent-filter>
    </service>
     <!-- use CTBackgroundJobService to target users on and above Android 21 (Lollipop) -->
    <service
        android:name="com.clevertap.android.sdk.CTBackgroundJobService"
        android:exported="false"
        android:permission="android.permission.BIND_JOB_SERVICE" />
```

Please see all the breaking changes done for [CleverTap Android SDK v4.0.0 here](https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTV4CHANGES.md)

**Comment by dattaprasadPegasus** [comment]
@darshanclevertap  I have made changes as per your suggestion but still getting runtime crash only Android < 5 ,
Crash Runtime : 
10-28 14:08:15.815 4989-5017/com.azam.sarafu E/dalvikvm: Could not find class 'dalvik.system.DelegateLastClassLoader', referenced from method com.google.android.gms.dynamite.DynamiteModule.zza
10-28 14:08:15.865 4989-4989/com.azam.sarafu E/dalvikvm: Could not find class 'android.app.job.JobScheduler', referenced from method com.clevertap.android.sdk.CleverTapAPI.createOrResetJobScheduler
10-28 14:08:15.945 4989-5037/com.azam.sarafu E/dalvikvm: Could not find class 'android.app.NotificationChannelGroup', referenced from method androidx.core.app.NotificationManagerCompat.getNotificationChannelGroup
10-28 14:08:15.955 4989-5040/com.azam.sarafu E/dalvikvm: Could not find class 'com.clevertap.android.sdk.pushnotification.amp.CTBackgroundJobService', referenced from method com.clevertap.android.sdk.ManifestValidator.checkReceiversServices
10-28 14:08:15.975 4989-4989/com.azam.sarafu E/dalvikvm: dlopen("/data/app-lib/com.azam.sarafu-1/libjscexecutor.so") failed: dlopen failed: could not load library "libjsc.so" needed by "libjscexecutor.so"; caused by library "libjsc.so" not found
10-28 14:08:15.975 4989-4989/com.azam.sarafu E/SoLoader: couldn't find DSO to load: libjscexecutor.so caused by: dlopen failed: could not load library "libjsc.so" needed by "libjscexecutor.so"; caused by library "libjsc.so" not found result: 0
10-28 14:08:15.985 4989-4989/com.azam.sarafu E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.azam.sarafu, PID: 4989
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.azam.sarafu/com.azam.sarafu.MainActivity}: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
        at android.app.ActivityThread.access$800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
        at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:90)
        at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:238)
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:281)
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87)
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39)
        at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:104)
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:90)
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:85)
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45)
        at com.azam.sarafu.MainActivity.onCreate(MainActivity.java:30)
        at android.app.Activity.performCreate(Activity.java:5231)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:80)
        at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:238) 
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:281) 
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87) 
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39) 
        at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:104) 
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:90) 
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:85) 
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45) 
        at com.azam.sarafu.MainActivity.onCreate(MainActivity.java:30) 
        at android.app.Activity.performCreate(Activity.java:5231) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.ExceptionInInitializerError
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015)
        at com.facebook.react.devsupport.DevServerHelper.<init>(DevServerHelper.java:132)
        at com.facebook.react.devsupport.DevSupportManagerImpl.<init>(DevSupportManagerImpl.java:183)
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
        at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:80) 
        at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:238) 
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:281) 
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87) 
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39) 
        at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:104) 
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:90) 
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:85) 
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45) 
        at com.azam.sarafu.MainActivity.onCreate(MainActivity.java:30) 
        at android.app.Activity.performCreate(Activity.java:5231) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 19
        at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
        at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263) 
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229) 
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015) 
        at com.facebook.react.devsupport.DevServerHelper.<init>(DevServerHelper.java:132) 
        at com.facebook.react.devsupport.DevSupportManagerImpl.<init>(DevSupportManagerImpl.java:183) 
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
        at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:80) 
        at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:238) 
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:281) 
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87) 
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39) 
        at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:104) 
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:90) 
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:85) 
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45) 
        at com.azam.sarafu.MainActivity.onCreate(MainActivity.java:30) 
        at android.app.Activity.performCreate(Activity.java:5231) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 



Here are my details configuration.

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

    implementation "com.google.android.gms:play-services-base:17.5.0"

    implementation 'com.google.firebase:firebase-analytics:17.6.0'
    implementation "androidx.core:core:1.3.0"
    implementation project(':clevertap-react-native')
    implementation project(':react-native-exception-handler')
    implementation project(':react-native-device-info')
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
implementation 'com.google.android.material:material:1.1.0'
    implementation 'androidx.fragment:fragment:1.2.5'
  implementation 'com.clevertap.android:clevertap-android-sdk:4.0.0'
    implementation 'com.google.firebase:firebase-messaging:20.2.4'
    implementation 'com.android.installreferrer:installreferrer:2.1'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'androidx.appcompat:appcompat:1.2.0'
debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group :'com.facebook.fbjni'
    }

    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group :'com.facebook.flipper'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group :'com.facebook.flipper'
    }

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}


//AndroidManifest.xml

       <service android:name="com.clevertap.android.sdk.pushnotification.fcm.FcmMessageListenerService">
    <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
</service>

<service
    android:name="com.clevertap.android.sdk.pushnotification.CTNotificationIntentService"
    android:exported="false">
    <intent-filter>
        <action android:name="com.clevertap.PUSH_EVENT" />
    </intent-filter>
</service>

        <meta-data
            android:name="CLEVERTAP_BACKGROUND_SYNC"
            android:value="1" /> 


//package.json
"clevertap-react-native": "^0.5.0",

**Comment by piyush-kukadiya** [comment]
@dattaprasadPegasus How is this CleverTap issue? Please check all `caused by:` lines provided by your stack trace to fix it.
