### ISSUE TITLE
We've integrated xiaomi push notification, it is working fine for xiaomi phones but we are receiving crashes on oppo and realme phones majorly.

### ISSUE THREAD

**Issue by Kamal-Walia** [CleverTap/clevertap-react-native#129]
Caused by java.lang.ClassNotFoundException
Didn't find class "com.clevertap.android.sdk.pushnotification.PushConstants$PushType" 

com.clevertap.android.xps.XpsConstants.<clinit> (XpsConstants.java)
com.clevertap.android.xps.XiaomiMessageReceiver.onReceiveRegisterResult (XiaomiMessageReceiver.java:8)
com.xiaomi.mipush.sdk.MessageHandleService.c (MessageHandleService.java:419)
com.xiaomi.mipush.sdk.MessageHandleService.a (MessageHandleService.java)
com.xiaomi.mipush.sdk.x.run (x.java:2)

**Comment by piyush-kukadiya** [comment]
@Kamal-Walia What version of SDK you are using? Also post full stack trace here.

**Comment by Kamal-Walia** [comment]
SDK version:- 0.4.5
Stack trace:- 
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/clevertap/android/sdk/pushnotification/PushConstants$PushType;
       at com.clevertap.android.xps.XpsConstants.<clinit>(XpsConstants.java)
       at com.clevertap.android.xps.XiaomiMessageReceiver.onReceivePassThroughMessage(XiaomiMessageReceiver.java:5)
       at com.xiaomi.mipush.sdk.MessageHandleService.c(MessageHandleService.java:246)
       at com.xiaomi.mipush.sdk.MessageHandleService.a(MessageHandleService.java)
       at com.xiaomi.mipush.sdk.x.run(x.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
Caused by java.lang.ClassNotFoundException: Didn't find class "com.clevertap.android.sdk.pushnotification.PushConstants$PushType" on path: DexPathList[[zip file "/data/app/live.video.shopping.simsim-rz4KAds9wFyLNuK9s-YFHQ==/base.apk", zip file "/data/app/live.video.shopping.simsim-rz4KAds9wFyLNuK9s-YFHQ==/split_config.arm64_v8a.apk", zip file "/data/app/live.video.shopping.simsim-rz4KAds9wFyLNuK9s-YFHQ==/split_config.en.apk", zip file "/data/app/live.video.shopping.simsim-rz4KAds9wFyLNuK9s-YFHQ==/split_config.xhdpi.apk"],nativeLibraryDirectories=[/data/app/live.video.shopping.simsim-rz4KAds9wFyLNuK9s-YFHQ==/lib/arm64, /data/app/live.video.shopping.simsim-rz4KAds9wFyLNuK9s-YFHQ==/base.apk!/lib/arm64-v8a, /data/app/live.video.shopping.simsim-rz4KAds9wFyLNuK9s-YFHQ==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/live.video.shopping.simsim-rz4KAds9wFyLNuK9s-YFHQ==/split_config.en.apk!/lib/arm64-v8a, /data/app/live.video.shopping.simsim-rz4KAds9wFyLNuK9s-YFHQ==/split_config.xhdpi.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at com.clevertap.android.xps.XpsConstants.<clinit>(XpsConstants.java)
       at com.clevertap.android.xps.XiaomiMessageReceiver.onReceivePassThroughMessage(XiaomiMessageReceiver.java:5)
       at com.xiaomi.mipush.sdk.MessageHandleService.c(MessageHandleService.java:246)
       at com.xiaomi.mipush.sdk.MessageHandleService.a(MessageHandleService.java)
       at com.xiaomi.mipush.sdk.x.run(x.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Comment by piyush-kukadiya** [comment]
@Kamal-Walia Can you check what version of `clevertap-android-sdk` is getting downloaded in your project dependency graph. Because `0.4.5` is dependent on [clevertap-android-sdk:3.8.2](https://github.com/CleverTap/clevertap-android-sdk/tree/3.8.2/clevertap-android-sdk/src/main/java/com/clevertap/android/sdk) which does not have package `com.clevertap.android.sdk.pushnotification`. We introduced push related breaking changes in [clevertap-android-sdk:4.0.0](https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTV4CHANGES.md#-push-notification-changes) which is supported by [clevertap-react-native:0.5.0](https://github.com/CleverTap/clevertap-react-native/blob/master/CHANGELOG.md#version-050-15th-october-2020)

**Comment by Kamal-Walia** [comment]
clever tap android SDK version is 3.9.1

**Comment by piyush-kukadiya** [comment]
You must use `3.8.2` for  `clevertap-react-native:0.4.5` or switch to latest SDK versions.

**Comment by Kamal-Walia** [comment]
Okay will try that and will update here.

**Comment by Aditi3** [comment]
Closing it due to inactivity, feel free to reopen if you need further help.
