### ISSUE TITLE
issue with the lasted version of node and yarn

### ISSUE THREAD

**Issue by MatthieuPeyrot** [CleverTap/clevertap-react-native#16]
Hi,

After I updated node (10.5.0) and yarn (1.7.0) 
 to the lastest version and i got this issue : 

```
Output:
fs.js:141
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:141:11)
    at Object.unlink (fs.js:912:14)
    at /Users/dev/voxist-app/node_modules/clevertap-react-native/install.js:15:16
    at ZipFile.<anonymous> (/Users/dev/voxist-app/node_modules/extract-zip/index.js:40:11)
    at ZipFile.emit (events.js:182:13)
    at FdSlicer.<anonymous> (/Users/dev/voxist-app/node_modules/yauzl/index.js:182:10)
    at Object.onceWrapper (events.js:273:13)

**Comment by MatthieuPeyrot** [comment]
Also at the beginning, I have those warning  

```
warning clevertap-react-native > npm > libcipm@1.6.3: This version mistakenly dropped node@4 compatibility in a semver-patch release. Please stay on 1.6.2 or update to 2 or latest
warning clevertap-react-native > npm > npm-registry-fetch@1.1.1: this version has a breaking change. use 1.1.0 or upgrade to latest
warning clevertap-react-native > npm > npm-registry-fetch > make-fetch-happen > socks-proxy-agent > socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

**Comment by Sunkari16** [comment]
facing same issue

**Comment by pwilkniss** [comment]
@MatthieuPeyrot @Sunkari16  apologies for the delay.  this should now be fixed.
