### ISSUE TITLE
On android - App crashes on opening 

### ISSUE THREAD

**Issue by jiteshwadia** [CleverTap/clevertap-react-native#21]
**issue:** 
On android, App keeps crashing on opening. Shows error message as "App keeps stopping"
On iOS, Works fine.

**Steps:**
```
react-native init TestApp
react-native run-ios --->  Works 
react-native run-android --->  Works 
npm install --save clevertap-react-native
react-native link clevertap-react-native
react-native run-android --->  App crashes here 

```

**Package.json**
```
{
  "name": "TestApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "clevertap-react-native": "^0.2.4",
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.3"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.1",
    "react-test-renderer": "16.6.0-alpha.8af6728"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Android Studio - Logcat** -- Filtered by Errors only 
```
2018-10-25 15:42:57.139 8501-8501/? E/memtrack: Couldn't load memtrack module (No such file or directory)
2018-10-25 15:42:57.139 8501-8501/? E/android.os.Debug: failed to load memtrack module: -2
2018-10-25 15:42:57.526 8514-8514/? E/memtrack: Couldn't load memtrack module (No such file or directory)
2018-10-25 15:42:57.527 8514-8514/? E/android.os.Debug: failed to load memtrack module: -2
2018-10-25 15:43:01.147 8562-8562/? E/memtrack: Couldn't load memtrack module (No such file or directory)
2018-10-25 15:43:01.147 8562-8562/? E/android.os.Debug: failed to load memtrack module: -2
2018-10-25 15:43:01.341 1308-1324/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
2018-10-25 15:43:01.435 8572-8594/com.testapp E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
2018-10-25 15:43:01.435 8572-8594/com.testapp E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
2018-10-25 15:43:02.042 8572-8598/com.testapp E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.testapp, PID: 8572
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/clevertap/react/CleverTapModule;
        at com.clevertap.react.CleverTapPackage.createNativeModules(CleverTapPackage.java:21)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:85)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1171)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1141)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1083)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:116)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:913)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.ClassNotFoundException: com.clevertap.react.CleverTapModule
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.clevertap.react.CleverTapPackage.createNativeModules(CleverTapPackage.java:21) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:85) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1171) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1141) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1083) 
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:116) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:913) 
        at java.lang.Thread.run(Thread.java:761) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/clevertap/android/sdk/SyncListener;
        at com.clevertap.react.CleverTapPackage.createNativeModules(CleverTapPackage.java:21) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:85) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1171) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1141) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1083) 
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:116) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:913) 
        at java.lang.Thread.run(Thread.java:761) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.clevertap.android.sdk.SyncListener" on path: DexPathList[[zip file "/data/app/com.testapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.testapp-1/lib/x86, /data/app/com.testapp-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.clevertap.react.CleverTapPackage.createNativeModules(CleverTapPackage.java:21) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:85) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1171) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1141) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1083) 
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:116) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:913) 
        at java.lang.Thread.run(Thread.java:761) 
2018-10-25 15:43:02.168 1677-5185/system_process E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
2018-10-25 15:43:02.168 1677-5185/system_process E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824

```

**android/build.gradle**

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}


task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}

```

**android/settings.gradle**

```
rootProject.name = 'TestApp'
include ':clevertap-react-native'
project(':clevertap-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/clevertap-react-native/android')

include ':app'

```

**Screenshot** - android
![screenshot_1540462351](https://user-images.githubusercontent.com/2070409/47493943-2abf9180-d86e-11e8-8f5b-9fe27fcbdf34.png)

**Comment by darshanclevertap** [comment]
@jiteshwadia 
Apologies for the delay in getting back to you.
Looking at the stack trace of the logs you have shared, it seems like you have not added the CleverTapModule in your MainActivity. Have you followed the [integration steps](https://github.com/CleverTap/clevertap-react-native/blob/master/docs/integration.md) here?
If not, please follow the steps mentioned in the integration document and let us know if the issue persists.

**Comment by darshanclevertap** [comment]
@jiteshwadia Did your issue get fixed? If you are still facing the issue please let us know.

**Comment by Aditi3** [comment]
Closing it due to inactivity, if you are still facing the issue reach out us at support@clevertap.com.

Thanks!
