### ISSUE TITLE
Android app just closes

### ISSUE THREAD

**Issue by bohrend** [CleverTap/clevertap-react-native#242]
after adding the required clever tap meta-tags inside application tag in the manifest, when I launch my android app on a physical device the app just closes immediately, but it works on the emulator.

logs show:

 --------- beginning of crash
2022-07-15 15:03:53.671 18739-18771/? E/AndroidRuntime: FATAL EXCEPTION: Thread-4
    Process: com.shop2shop, PID: 18739
    java.lang.SecurityException: getDataNetworkTypeForSubscriber
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
        at android.os.Parcel.createException(Parcel.java:2360)
        at android.os.Parcel.readException(Parcel.java:2343)
        at android.os.Parcel.readException(Parcel.java:2285)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8764)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3031)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2995)
        at com.clevertap.android.sdk.DeviceInfo$DeviceCachedInfo.getNetworkType(DeviceInfo.java:618)
        at com.clevertap.android.sdk.DeviceInfo$DeviceCachedInfo.<init>(DeviceInfo.java:546)
        at com.clevertap.android.sdk.DeviceInfo.getDeviceCachedInfo(DeviceInfo.java:81)
        at com.clevertap.android.sdk.DeviceInfo.access$000(DeviceInfo.java:23)
        at com.clevertap.android.sdk.DeviceInfo$1.run(DeviceInfo.java:52)
        at java.lang.Thread.run(Thread.java:923)
2022-07-15 15:03:53.673 18739-18739/? D/SoLoader: init start
2022-07-15 15:03:53.673 18739-18764/? E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.shop2shop, PID: 18739
    java.lang.SecurityException: getDataNetworkTypeForSubscriber
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
        at android.os.Parcel.createException(Parcel.java:2360)
        at android.os.Parcel.readException(Parcel.java:2343)
        at android.os.Parcel.readException(Parcel.java:2285)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8764)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3031)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2995)
        at com.clevertap.android.sdk.DeviceInfo$DeviceCachedInfo.getNetworkType(DeviceInfo.java:618)
        at com.clevertap.android.sdk.DeviceInfo$DeviceCachedInfo.<init>(DeviceInfo.java:546)
        at com.clevertap.android.sdk.DeviceInfo.getDeviceCachedInfo(DeviceInfo.java:81)
        at com.clevertap.android.sdk.DeviceInfo.access$000(DeviceInfo.java:23)
        at com.clevertap.android.sdk.DeviceInfo$1.run(DeviceInfo.java:52)
        at java.lang.Thread.run(Thread.java:923)

```  <meta-data
            android:name="CLEVERTAP_ACCOUNT_ID"
            android:value="removed"/>
        <meta-data
            android:name="CLEVERTAP_TOKEN"
            android:value="removed"/>
        <meta-data
            android:name="CLEVERTAP_USE_GOOGLE_AD_ID"
            android:value="1"/>
    </application>

mainApplication class for react native looks like this:
@Override
  public void onCreate() {
    CleverTapAPI clevertapDefaultInstance = CleverTapAPI.getDefaultInstance(getApplicationContext());
    CleverTapAPI.setUIEditorConnectionEnabled(false);
    ActivityLifecycleCallback.register(this);
    super.onCreate();
    etc
  }

**Comment by piyush-kukadiya** [comment]
@bohrend Please check this out https://github.com/CleverTap/clevertap-android-sdk/issues/148
