### ISSUE TITLE
Unable to start receiver e.c.b.b.openContextMenu: java.lang.ClassNotFoundException: com.clevertap.android.sdk.Logger

### ISSUE THREAD

**Issue by Naveen9453** [CleverTap/clevertap-react-native#297]
Hi Team,   Facing crash when receiving push notification on Android Platform
--------- beginning of crash
2023-02-03 09:36:36.723 14660-14660/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxx.xxxxx, PID: 14660
    java.lang.RuntimeException: Unable to start receiver e.c.b.b.openContextMenu: java.lang.ClassNotFoundException: com.clevertap.android.sdk.Logger
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4619)
        at android.app.ActivityThread.access$1900(ActivityThread.java:284)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2277)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:334)
        at android.app.ActivityThread.main(ActivityThread.java:8333)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)
     Caused by: java.lang.ClassNotFoundException: com.clevertap.android.sdk.Logger
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at e.c.b.b.openContextMenu.onReceive(Unknown Source:1158)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4610)
        at android.app.ActivityThread.access$1900(ActivityThread.java:284) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2277) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:233) 
        at android.os.Looper.loop(Looper.java:334) 
        at android.app.ActivityThread.main(ActivityThread.java:8333) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065) 

Platform- Android
"react-native": "0.68.0"
 "clevertap-react-native": "0.9.4"

Please Help on priority.

**Comment by piyush-kukadiya** [comment]
@Naveen9453 This is already fixed in RenderMax `1.0.2`, please use latest version of RenderMax https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTRENDERMAXCHANGELOG.md . You can try using `1.0.2` however if there is any comile time issue, you may have to update `clevertap-react-native` to latest version.

**Comment by Naveen9453** [comment]
@piyush-kukadiya  Thanks for quick response. The issue has been resolved.
