### ISSUE TITLE
How to pass remote-message to RNFirebaseMessagingService if the message is not from CleverTap

### ISSUE THREAD

**Issue by uraniumreza** [CleverTap/clevertap-react-native#58]
I was trying to pass the RemoteMessage to RNFirebaseMessagingService if it's not from CleverTap by this - 

```
RNFirebaseMessagingService rnf = new RNFirebaseMessagingService();
rnf.onMessageReceived(message);
```

But I'm getting an error - 

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
        at android.content.ContextWrapper.getApplicationContext(ContextWrapper.java:109)
        at io.invertase.firebase.messaging.RNFirebaseMessagingService.onMessageReceived(RNFirebaseMessagingService.java:47)
```

**Comment by darshanclevertap** [comment]
@uraniumreza Could you provide some more logs? From these logs, there doesn't seem to be anything wrong with CleverTap.
