### ISSUE TITLE
[Android] NoSuchMethodError: No virtual method getGooglePlayInstantParam()

### ISSUE THREAD

**Issue by Skullflow** [CleverTap/clevertap-react-native#67]
Hi,

I'm integrating Clevertap on react native v0.59.10.

I've got this error at runtime:
java.lang.NoSuchMethodError: No virtual method getGooglePlayInstantParam()Z in class Lcom/android/installreferrer/api/ReferrerDetails; or its super classes (declaration of 'com.android.installreferrer.api.ReferrerDetails' appears in /data/app/***-RSESYs2QgccRwLg-H07cZw==/base.apk!classes2.dex)
        at com.clevertap.android.sdk.CleverTapAPI$43.onInstallReferrerSetupFinished(CleverTapAPI.java:6379)
        at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(InstallReferrerClientImpl.java:222)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1770)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1802)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

I tried both com.clevertap.android:clevertap-android-sdk:3.6.0 and com.clevertap.android:clevertap-android-sdk:3.6.3

How can i resolve this?

Thanks

**Comment by Aditi3** [comment]
Hi @Skullflow 

Can you help me with the npm package version of the CleverTap React Native SDK that you are installing?

**Comment by Skullflow** [comment]
I'm using the last one (0.3.8)

**Comment by Aditi3** [comment]
Thank you for the prompt response. Surely, we will look into it.

In the meantime, I would recommend you to install the previous version of our package that is 0.3.7

**Comment by kumaratulismu** [comment]
Hey @Skullflow ,

You need to include the undermentioned dependency in the build.gradle file.

**implementation 'com.android.installreferrer:installreferrer:1.1'**

It is mandatory now with the release V0.3.8 to support the Google's new Install Referrer API.

For more information you can refer : https://developer.android.com/google/play/installreferrer/library.html

**Comment by Skullflow** [comment]
Hi @kumaratulismu,

I added installreferrer library and seems like to work now.

Thanks for your help.
